trigger:
 tags:
   include:
     - perf-test*
variables:
  ENVIRONMENT: dev
pool: cholpona

steps:
- script: |
    [[ "$BUILD_SOURCEBRANCH" == refs/tags/perf-test* && "$ENVIRONMENT" == "dev" ]] && NAMESPACE="perf-test" && echo "$NAMESPACE" || echo "1"
    git fetch
    git merge origin/main

