trigger: 
  branches:
    include:
    - '*'
pool: cholpona

resources:
  repositories: 
  - repository: ag-fraud-advisor
    type: git 
    name: ag-fraud-advisor/ag-fraud-advisor
    ref: refs/heads/Test
stages: 
- stage: sw
  jobs:
  - job: sw
    steps:
    - script: |
        git config user.email "$(Build.RequestedForEmail)"
        git config user.name "$(Build.RequestedFor)"
        current_branch=$(echo $(Build.SourceBranch) | awk -F '/' '{print $3}')
        # git fetch -a
        # git checkout origin/main
        # git pull origin main
        # git checkout -b '$(current_branch)'
        # git merge origin main
        # echo $current_branch
        git checkout main
        git pull origin main
        git merge $current_branch
        git push origin main
      
  
