trigger:
 tags:
   include:
     - perf-test*

pool: cholpona

steps:
- script: |
    [[ "$Build.SourceBranch" == refs/tags/perf-test* && "$ENVIRONMENT" == "dev" ]] && NAMESPACE="perf-test" || echo "1"

