trigger: 
  branches:
    include:
    - '*'
variables:
  ENVIRONMENT: dev
pool: cholpona

resources:
  repositories: 
  - repository: ag-fraud-advisor
    type: git 
    name: ag-fraud-advisor/ag-fraud-advisor
    ref: refs/heads/master
    
steps:
- script: |
    echo $(Build.Repository.Name)
    echo $(Build.RequestedFor)
