trigger: 
  branches:
    include:
    - '*'
pool: cholpona

resources:
  repositories: 
  - repository: ag-fraud-advisor
    type: git 
    name: ag-fraud-advisor/ag-fraud-advisor
    ref: refs/heads/Test
stages: 
- template: templ.yaml@ag-fraud-advisor
  - job: sw
    steps:
    - script: |
        echo 'stage is working'
         
      
  
