trigger: 
  branches:
    include:
    - '*'
pool: cholpona

resources:
  repositories: 
  - repository: ag-fraud-advisor
    type: git 
    name: ag-fraud-advisor/ag-fraud-advisor
    ref: refs/heads/Test
stages: 
# - template: templ.yaml@ag-fraud-advisor
- stage:
  - job: sw
    steps:
    - script: |
        git config user.email $(Build.RequestedForEmail)
        git config user.name $(Build.RequestedFor)
         
      
  
