trigger: 
  branches:
    include:
    - '*'
pool: cholpona

resources:
  repositories: 
  - repository: ag-fraud-advisor
    type: git 
    name: ag-fraud-advisor/ag-fraud-advisor
    ref: refs/heads/Test
stages: 
- stage: sw
  jobs:
  - job: sw
    steps:
    - script: |
        PAT='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'
        git config user.email "$(Build.RequestedForEmail)"
        git config user.name "$(Build.RequestedFor)"
        git clone git@github.com:abdisuhanova/gke.git
        cd gke
        git merge origin/Test
        git push origin main
      
