trigger:
  tags:
    include:
      - perf-test*

pool:
  name: cholpona

steps:
- script: |
    if [[ "$Build.SourceBranch" == refs/tags/perf-test* && "$ENVIRONMENT" == "dev" ]]; then
      NAMESPACE="perf-test"
      echo "Namespace set to perf-test"
    else
      echo "Condition not met"
      exit 1
    fi
  displayName: 'Set Namespace for Perf Test'
