trigger:
 tags:
   include:
     - perf-test*
variables:
  ENVIRONMENT: dev
pool: cholpona

resources:
  repositories: 
  - repository: ag-fraud-advisor
    type: git 
    name: ag-fraud-advisor/ag-fraud-advisor
    ref: refs/heads/master
    
steps:
- script: |
    [[ "$BUILD_SOURCEBRANCH" == refs/tags/perf-test* && "$ENVIRONMENT" == "dev" ]] && NAMESPACE="perf-test" || echo "1"
- template: templ.yaml@ag-fraud-advisor
